// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.ElementPositioner = (function() {

    function ElementPositioner() {
      this.destroyControlPanel = __bind(this.destroyControlPanel, this);

      this.createControlPanel = __bind(this.createControlPanel, this);

      this.restoreClickBindingsToElements = __bind(this.restoreClickBindingsToElements, this);

      this.removeClickBindingsFromElements = __bind(this.removeClickBindingsFromElements, this);

      this.displayResult = __bind(this.displayResult, this);

      this.initDraggables = __bind(this.initDraggables, this);

      this.deactivate = __bind(this.deactivate, this);

      this.activate = __bind(this.activate, this);
      this.draggable = null;
      this.active = false;
      this.controlPanel = this.createControlPanel();
    }

    ElementPositioner.prototype.activate = function(elements) {
      this.elements = elements;
      this.removeClickBindingsFromElements();
      this.initDraggables();
      this.elements.css({
        cursor: 'move'
      });
      this.active = true;
      return this.displayResult();
    };

    ElementPositioner.prototype.deactivate = function(closePanel) {
      if (closePanel == null) {
        closePanel = false;
      }
      if (closePanel) {
        this.destroyControlPanel();
      }
      this.restoreClickBindingsToElements();
      this.draggable.draggable("destroy");
      this.active = false;
      this.elements.css({
        cursor: 'inherit'
      });
      return this.displayResult();
    };

    ElementPositioner.prototype.initDraggables = function() {
      return this.draggable = this.elements.draggable({
        stack: '*',
        drag: this.displayResult
      });
    };

    ElementPositioner.prototype.displayResult = function() {
      var styleString,
        _this = this;
      styleString = "";
      this.elements.each(function(i, e) {
        var left, selector, top, z;
        e = $(e);
        selector = e.attr('id') != null ? "#" + (e.attr('id')) : e.getSelector();
        left = parseInt(e.css('left'), 10);
        top = parseInt(e.css('top'), 10);
        left = isNaN(left) ? 'auto' : "" + left + "px";
        top = isNaN(top) ? 'auto' : "" + top + "px";
        z = e.css('z-index');
        return styleString += "" + selector + " { left: " + left + "; top: " + top + "; z-index: " + z + "; }\n";
      });
      return this.controlPanel.find('.element-positioner-result').text(styleString);
    };

    ElementPositioner.prototype.removeClickBindingsFromElements = function() {
      return this.elements.unbind('click');
    };

    ElementPositioner.prototype.restoreClickBindingsToElements = function() {
      return this.elements.unbind('click');
    };

    ElementPositioner.prototype.createControlPanel = function() {
      var acceptSelector, handle, panel, previewSelector, result, selector, style,
        _this = this;
      previewSelector = function(e) {
        var target, val;
        target = $(e.target);
        val = target.val();
        $('.element-positioner-selected').removeClass('element-positioner-selected');
        return $(val).addClass('element-positioner-selected');
      };
      acceptSelector = function(e) {
        var target;
        target = $(e.target);
        _this.activate($(target.val()));
        target.remove();
        return $('.element-positioner-selected').removeClass('element-positioner-selected');
      };
      style = $('<style>').attr('type', 'text/css');
      style.html('.element-positioner-selected{ background-color:yellow; outline:2px solid yellow; opacity:.8}');
      $('head').append(style);
      panel = $('<div>').attr('id', 'element-positioner-panel');
      handle = $('<div>').addClass('element-positioner-handle');
      result = $('<textarea>').addClass('element-positioner-result').click(function(e) {
        return $(e.target).select();
      });
      selector = $('<input>').addClass('element-positioner-selector');
      selector.change(acceptSelector);
      selector.keyup(previewSelector);
      panel.append(handle);
      panel.append(selector);
      panel.append(result);
      panel.draggable({
        handle: handle
      });
      $('body').append(panel);
      return panel;
    };

    ElementPositioner.prototype.destroyControlPanel = function() {
      return this.controlPanel.remove();
    };

    return ElementPositioner;

  })();

}).call(this);
